# Generated by Django 2.2.19 on 2023-03-17 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230315_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Избранное'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=200, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(verbose_name='Описание рецепта'),
        ),
        migrations.AlterField(
            model_name='recipeingredientrelations',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество ингредиентов'),
        ),
        migrations.AddConstraint(
            model_name='basket',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='Нельзя повторно добавлять рецепт в корзину.'),
        ),
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='Нельзя повторно добавлять рецепт в избранное.'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredientrelations',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='Необходима уникальная связь междурецептом и ингредиентом.'),
        ),
        migrations.AddConstraint(
            model_name='recipetagrelations',
            constraint=models.UniqueConstraint(fields=('tag', 'recipe'), name='Необходима уникальная связь между рецептом и тегом.'),
        ),
    ]
