# Generated by Django 2.2.19 on 2023-03-19 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230317_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientrelations',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipes.Ingredient'),
        ),
    ]
